-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.886 sec <<< FAILURE! - in TestSuite
to_fail(mt.trial_mv)  Time elapsed: 0.043 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at mt.trial_mv.to_fail(trial_mv.java:15)

